# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-28 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=30)),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('css_class', models.CharField(blank=True, max_length=100, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatFormation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_catformation', models.CharField(max_length=30)),
                ('pitch', models.CharField(blank=True, max_length=300, null=True)),
                ('css_icon', models.CharField(blank=True, max_length=100, null=True)),
                ('css_class', models.CharField(blank=True, max_length=200, null=True)),
                ('css_color', models.CharField(blank=True, max_length=30, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(default='', help_text='indiquer un nom unique pour url', max_length=64, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='ChapitreFormation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_chapitre', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('documentation_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_formation', models.CharField(max_length=50)),
                ('pitch', models.CharField(blank=True, max_length=300, null=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('niveau', models.CharField(choices=[('Débutant', '0'), ('Avancé', '1'), ('Expert', '2')], default='0', max_length=50)),
                ('public', models.CharField(max_length=100)),
                ('objectif', models.CharField(blank=True, max_length=300, null=True)),
                ('formateur', models.CharField(blank=True, default='Hugo Roussaffa', max_length=50)),
                ('methode', models.CharField(max_length=100)),
                ('duree', models.CharField(choices=[('une demi journée', '1/2j'), ('une journée', '1j'), ('2 jours', '2j'), ('3 jours', '3j')], default='', max_length=50)),
                ('tarif', models.CharField(max_length=15)),
                ('css_icon', models.CharField(blank=True, max_length=15, null=True)),
                ('css_class', models.CharField(blank=True, max_length=100, null=True)),
                ('css_color', models.CharField(blank=True, max_length=100, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(default='', help_text='indiquer un nom unique pour url', max_length=64, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleFormation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_module', models.CharField(max_length=100)),
                ('objectif', models.CharField(blank=True, max_length=300, null=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(default='', help_text='indiquer un nom unique pour url', max_length=64, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_reference', models.CharField(max_length=15)),
                ('pitch', models.CharField(blank=True, max_length=30, null=True)),
                ('css_icon', models.CharField(blank=True, max_length=15, null=True)),
                ('css_class', models.CharField(blank=True, max_length=100, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(default='', help_text='indiquer un nom unique pour url', max_length=64, verbose_name='slug')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_secteur', models.CharField(max_length=15)),
                ('css_class', models.CharField(blank=True, max_length=100, null=True)),
                ('css_icon', models.CharField(blank=True, max_length=30, null=True)),
                ('css_color', models.CharField(blank=True, max_length=30, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(default='', help_text='indiquer un nom unique pour url', max_length=64, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_section', models.CharField(max_length=30)),
                ('level', models.CharField(choices=[('navbar-top', 'navbar-top'), ('navbar-top-sub1', 'navbar-top-sub1'), ('navbar-top-sub2', 'navbar-top-sub2'), ('navbar-verticale', 'navbar-verticale')], default='indéfini', max_length=50)),
                ('css_icon', models.CharField(blank=True, max_length=100, null=True)),
                ('css_div_class', models.CharField(blank=True, max_length=100, null=True)),
                ('css_ahref_class', models.CharField(blank=True, max_length=100, null=True)),
                ('css_datacategory', models.CharField(choices=[('products', 'products'), ('help', 'help'), ('documentation', 'documentation'), ('use-cases', 'use-cases'), ('', 'aucun')], default='', max_length=50)),
                ('slug', models.SlugField(default='', help_text='indiquer un nom unique pour url', max_length=64, verbose_name='slug')),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=30)),
                ('pitch', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('css_icon', models.CharField(blank=True, max_length=15, null=True)),
                ('css_class', models.CharField(blank=True, max_length=100, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(default='', help_text='indiquer un nom unique pour url', max_length=64, verbose_name='slug')),
                ('categorie_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_soft', models.CharField(max_length=15)),
                ('pitch', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('css_icon', models.CharField(blank=True, max_length=15, null=True)),
                ('css_class', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(default='', help_text='indiquer un nom unique pour url', max_length=64, verbose_name='slug')),
                ('actif', models.BooleanField(default=True)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.Image')),
            ],
        ),
        migrations.AddField(
            model_name='formation',
            name='logiciels',
            field=models.ManyToManyField(blank=True, to='website.Software'),
        ),
        migrations.AddField(
            model_name='formation',
            name='prerequis',
            field=models.ManyToManyField(blank=True, to='website.Formation'),
        ),
        migrations.AddField(
            model_name='formation',
            name='programme',
            field=models.ManyToManyField(blank=True, to='website.ModuleFormation'),
        ),
        migrations.AddField(
            model_name='chapitreformation',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.ModuleFormation'),
        ),
        migrations.AddField(
            model_name='catformation',
            name='formations',
            field=models.ManyToManyField(blank=True, to='website.Formation'),
        ),
        migrations.AddField(
            model_name='catformation',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.Image'),
        ),
    ]
