# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-09 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitreformation',
            name='slug',
            field=models.SlugField(default='', help_text='indiquer un nom unique pour url', max_length=64, verbose_name='slug'),
        ),
    ]
