# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-28 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catformation',
            name='image',
        ),
        migrations.AddField(
            model_name='catformation',
            name='urlimage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
