# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-09 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
        ('website', '0002_chapitreformation_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_realisation', models.CharField(max_length=15)),
                ('pitch', models.CharField(blank=True, max_length=30, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.Image')),
            ],
        ),
        migrations.AlterField(
            model_name='personne',
            name='position',
            field=models.CharField(choices=[('Gérant', 'gérant'), ('Associé', 'associé'), ('Associée', 'associée'), ('Colaborateur', 'Colaborateur'), ('Colaboratrice', 'Colaboratrice'), ('Salarié', 'salarié'), ('Salariée', 'salariée'), ('aucun', 'aucun')], default='associé', max_length=50),
        ),
    ]
