# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-25 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20161209_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='reference',
            field=models.ManyToManyField(blank=True, to='website.Reference'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='service',
            field=models.ManyToManyField(blank=True, to='website.Service'),
        ),
    ]
