# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-11 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20161111_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_personne', models.CharField(max_length=15)),
                ('type_personne', models.CharField(choices=[('Equipe', 'equipe'), ('client', 'client'), ('fournisseur', 'fournisseur'), ('aucun', 'aucun')], default='equipe', max_length=50)),
                ('postion', models.CharField(choices=[('Associé', 'associé'), ('Prestataire', 'prestataire'), ('Salarié', 'salarié'), ('aucun', 'aucun')], default='associé', max_length=50)),
                ('fonction', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_image', models.CharField(max_length=18)),
                ('css_icon', models.CharField(blank=True, max_length=15, null=True)),
                ('css_class', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(default='', help_text='indiquer un nom unique pour url', max_length=64, verbose_name='slug')),
            ],
        ),
    ]
