# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-11 11:41
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
        ('website', '0004_personne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='nom_image',
        ),
        migrations.AddField(
            model_name='personne',
            name='photo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.Image'),
        ),
    ]
