# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-12 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20161111_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='nom_personne',
            field=models.CharField(max_length=30),
        ),
    ]
