# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-12 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20161112_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personne',
            old_name='postion',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='personne',
            name='fonction',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
