# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-13 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_service_css_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='css_color',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
