# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-14 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_categorie_css_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
