# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-14 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_personne_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='type_personne',
            field=models.CharField(choices=[('equipe', 'equipe'), ('client', 'client'), ('fournisseur', 'fournisseur'), ('aucun', 'aucun')], default='equipe', max_length=50),
        ),
    ]
