# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-14 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20161114_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='landpage',
        ),
    ]
