# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-14 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_service_landpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='landpage',
            field=models.BooleanField(default=False),
        ),
    ]
