# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-14 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_service_landpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='pitch',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
