# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-14 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_categorie_pitch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='pitch',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='pitch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='pitch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
