# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-15 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20161114_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='html_page',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
