# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_secteur_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(default='', help_text='indiquer un nom unique pour url', max_length=64, verbose_name='slug'),
        ),
    ]
