# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_section_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='pitch',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
