# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-15 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20161115_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='html_page',
            field=models.CharField(default='<p></p>', max_length=10000),
        ),
    ]
