# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20161020_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catformation',
            name='pitch',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
