# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20161020_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catformation',
            name='css_class',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='catformation',
            name='css_icon',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
