# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-16 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='secteur',
            name='pitch',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
