# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-16 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
        ('website', '0022_secteur_pitch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_plan', models.CharField(max_length=15)),
                ('tarif', models.PositiveSmallIntegerField()),
                ('pitch', models.CharField(blank=True, max_length=30, null=True)),
                ('contenu_html', models.CharField(blank=True, max_length=500, null=True)),
                ('css_icon', models.CharField(blank=True, max_length=15, null=True)),
                ('css_class', models.CharField(blank=True, max_length=100, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(default='', help_text='indiquer un nom unique pour url', max_length=64, verbose_name='slug')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.Image')),
                ('secteur', models.ManyToManyField(blank=True, to='website.Secteur')),
            ],
        ),
    ]
