# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20161020_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catformation',
            old_name='nom_categorie',
            new_name='nom_catformation',
        ),
        migrations.AddField(
            model_name='catformation',
            name='slug',
            field=models.SlugField(default='', help_text='indiquer un nom unique pour url', max_length=64, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='formation',
            name='slug',
            field=models.SlugField(default='', help_text='indiquer un nom unique pour url', max_length=64, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='reference',
            name='slug',
            field=models.SlugField(default='', help_text='indiquer un nom unique pour url', max_length=64, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='software',
            name='slug',
            field=models.SlugField(default='', help_text='indiquer un nom unique pour url', max_length=64, verbose_name='slug'),
        ),
    ]
