# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-16 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='pitch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
