# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20161020_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='catformation',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='software',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
