# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-16 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20161116_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='contenu_html',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
