# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20161020_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catformation',
            name='nom_catformation',
            field=models.CharField(max_length=30),
        ),
    ]
