# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-16 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20161116_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='contenu_html',
        ),
        migrations.AddField(
            model_name='plan',
            name='assitance_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='atelier_nombre',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='consultance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='datapack_IGN_licence_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='datapack_opendata_update_frequency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='formation_Qgis_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='maintenance_available',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='projet_qgis_nombre',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='servicesTrue',
            field=models.ManyToManyField(blank=True, to='website.Service'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='css_icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='nom_plan',
            field=models.CharField(max_length=30),
        ),
    ]
