# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-16 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20161116_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='servicesTrue',
            new_name='services_available',
        ),
    ]
