# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20161021_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='css_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
