# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-16 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20161116_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='formation_Qgis_level',
            field=models.CharField(choices=[('Débutant', '0'), ('Avancé', '1'), ('Expert', '2')], default='0', max_length=50),
        ),
    ]
