# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-16 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20161116_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='datapack_IGN_licence_level',
        ),
        migrations.AddField(
            model_name='plan',
            name='datapack_IGN_licence_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
