# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20161021_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='prerequis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Formation'),
        ),
    ]
