# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20161021_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='prerequis',
        ),
        migrations.AddField(
            model_name='formation',
            name='prerequis',
            field=models.ManyToManyField(blank=True, related_name='_formation_prerequis_+', to='website.Formation'),
        ),
    ]
