# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-16 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20161116_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='services_available',
            new_name='servicesAvailable',
        ),
    ]
