# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-16 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_auto_20161116_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='atelier',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='assitance_level',
            field=models.CharField(choices=[('Base de connaissance évolutive', '0'), ('Téléassistant', '1'), ('Support helpdesk, déplacement ', '2'), ('Intervention consultant, ingénieur ', '3'), ('Urgence ', '4')], default='0', max_length=50),
        ),
    ]
