# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-16 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_auto_20161116_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='determinant',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
