# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_auto_20161021_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='duree',
            field=models.CharField(choices=[('une demi journée', '1/2j'), ('une journée', '1j'), ('2 jours', '2j'), ('3 jours', '3j')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='formation',
            name='niveau',
            field=models.CharField(choices=[('Débutant', '0'), ('Avancé', '1'), ('Expert', '2')], default='', max_length=50),
        ),
    ]
