# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-16 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_formation_determinant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='determinant',
        ),
        migrations.AddField(
            model_name='secteur',
            name='determinant',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
