# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-18 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_auto_20161116_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='maintenance_available',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='pitch',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
