# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-18 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_auto_20161118_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='position',
            field=models.CharField(choices=[('Fondateur', 'fondateur'), ('Associé', 'associé'), ('Prestataire', 'prestataire'), ('Salarié', 'salarié'), ('aucun', 'aucun')], default='associé', max_length=50),
        ),
    ]
