# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-18 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_auto_20161118_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='secteur',
            name='description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
