# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-19 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
