# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-19 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_auto_20161119_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='nom_produit',
            field=models.CharField(max_length=100),
        ),
    ]
