# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-20 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_auto_20161119_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='secteur',
        ),
        migrations.AddField(
            model_name='produit',
            name='secteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Secteur'),
        ),
        migrations.RemoveField(
            model_name='produit',
            name='service',
        ),
        migrations.AddField(
            model_name='produit',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Service'),
        ),
    ]
