# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-20 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_auto_20161120_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='livrable',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='produits_lie',
            field=models.ManyToManyField(blank=True, to='website.Produit'),
        ),
        migrations.AddField(
            model_name='produit',
            name='unité',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='url_documentation_blog',
            field=models.URLField(blank=True, null=True),
        ),
    ]
