# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-20 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_auto_20161120_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='produits_lie',
            new_name='produits_lié',
        ),
    ]
