# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-21 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
        ('website', '0044_auto_20161120_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livrable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_livrable', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=2500, null=True)),
                ('css_icon', models.CharField(blank=True, max_length=20, null=True)),
                ('css_class', models.CharField(blank=True, max_length=100, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='produit',
            name='livrable',
        ),
        migrations.AddField(
            model_name='produit',
            name='livrable',
            field=models.ManyToManyField(blank=True, to='website.Livrable'),
        ),
    ]
