# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-22 08:14
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
        ('website', '0045_auto_20161121_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='secteur',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.Image'),
        ),
    ]
