# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-22 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_secteur_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tooltip',
            field=models.CharField(default='<span class="tooltip"></span>', max_length=10000),
        ),
    ]
