# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-22 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_service_tooltip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='atelier_nombre',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
