# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-22 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_auto_20161122_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='atelier_nombre',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
