# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-09 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0051_auto_20161209_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='produit_lié',
            new_name='produit_link',
        ),
    ]
